### ISSUE TITLE
A detail description of the final output

### ISSUE THREAD

**Issue by daisykuma22** [ziyewang/MetaBinner#21]
Dear Ziye:

Thank you for this excellent binning software. I am a little confused about the output file "metabinner_result.tsv", i gusses the first column shows the contig, and what the numbers in second column means. Plus, i want to confirm if the bins in the dir "kmeans_length_weight_X_t_logtrans_result.tsv_bins" are the final bins?

All the best

**Comment by ziyewang** [comment]
Thanks for using MetaBinner.
The "metabinner_result.tsv" is the final output, and the first column shows the contig ID and the the numbers in the second column means the bin ID. 
Please find the corresponding bins in: ${output_dir}/metabinner_res/ensemble_res/greedy_cont_weight_3_mincomp_50.0_maxcont_15.0_bins/ensemble_3logtrans/addrefined2and3comps/greedy_cont_weight_3_mincomp_50.0_maxcont_15.0_bins

Best,
Ziye

**Comment by AnyiHu** [comment]
Hi Ziye,

Thanks for developing this great tool. I just want to ask where I can find the tsv (or txt) file that show the completeness and contamination information of final bins (those in greedy_cont_weight_3_mincomp_50.0_maxcont_15.0_bins). Thanks.

Best,
Anyi

**Comment by ziyewang** [comment]
> Hi Ziye,
> 
> Thanks for developing this great tool. I just want to ask where I can find the tsv (or txt) file that show the completeness and contamination information of final bins (those in greedy_cont_weight_3_mincomp_50.0_maxcont_15.0_bins). Thanks.
> 
> Best, Anyi

Hi, Anyi,

Thanks. The completeness and contamination values used in our program are estimated using a simplified version of CheckM. We don't provide the evaluation results because the evaluation results may be different while using different versions of CheckM. If you would like to compare the performance of MetaBinner with other binners or figure out the quality of the bins, I recommend running CheckM on the output bins. 

Best,
Ziye
