### ISSUE TITLE
SafetyError - Incorrect size

### ISSUE THREAD

**Issue by Georgios-Filis** [ziyewang/MetaBinner#28]
Dear Ziye Wang,
Thank you for your work. I had successfully installed MetaBinner via bioconda in the past. Recently I had to install it in a new conda environment. Unfortunately, I get the following error either by trying to install it through Bioconda or through the metabinner_env.yaml file:

SafetyError: The package for checkm-genome located at /home/user/anaconda3/pkgs/checkm-genome-1.1.3-py_1
appears to be corrupted. The path 'site-packages/checkm/DATA_CONFIG'
has an incorrect size.
  reported size: 215 bytes
  actual size: 242 bytes

When trying the installation through Bioconda I also get the message:

ClobberError: The package 'conda-forge/linux-64::sqlite-3.32.3-hcee41ef_1' cannot be installed due to a
path collision for 'include/sqlite3.h'.
This path already exists in the target prefix, and it won't be removed by
an uninstall action in this transaction. The path appears to be coming from
the package 'conda-forge/linux-64::libsqlite-3.44.2-h2797004_0', which is already installed in the prefix.

Eventually, MetaBinner is not installed properly and cannot run. I have tried to install different versions of checkm-genome by modifying its version in the yaml file (e.g., with a version above 1.1.3 such as 1.2.2), but to no avail. Do you know what is causing this and what can I do to fix this error?

Sincerely,
Georgios Filis

**Comment by ziyewang** [comment]
Hi,

"SafetyError: The package for checkm-genome located at /home/user/anaconda3/pkgs/checkm-genome-1.1.3-py_1
appears to be corrupted. The path 'site-packages/checkm/DATA_CONFIG'
has an incorrect size.
reported size: 215 bytes
actual size: 242 bytes" 

This issue might be due to the presence of another version of CheckM already installed, and it may not affect its usage, or alternatively, you could try uninstalling CheckM and then reinstalling it.

Best,
Ziye
