### ISSUE TITLE
Error running bin command

### ISSUE THREAD

**Issue by rgtaketani** [ziyewang/MetaBinner#8]
I am trying to run metabinner and I got this error.

/home/data/mmeg_ngs/rodrigo_taketani/condaenvs/metabinner/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
2021-11-22 20:44:32,204 - Input arguments:
2021-11-22 20:44:32,204 - Contig_file:	/home/data/mmeg_ngs_seqs_database/MAG/megahit_out/final.contigs.fa
2021-11-22 20:44:32,204 - Coverage_profiles:	/home/data/mmeg_ngs_seqs_database/MAG/coverage_profile.tsv
2021-11-22 20:44:32,204 - Composition_profiles:	/home/data/mmeg_ngs_seqs_database/MAG/megahit_out/kmer_4_f1000.csv
2021-11-22 20:44:32,205 - Output file path:	/home/data/mmeg_ngs_seqs_database/MAG/metabinner/metabinner_res/result.tsv
2021-11-22 20:44:32,205 - Predefined Clusters:	Auto
2021-11-22 20:44:32,205 - The number of threads:	10
Traceback (most recent call last):
  File "component_binning.py", line 403, in <module>
    X_t, namelist, mapObj, X_cov, X_com = gen_X(com_file, cov_file)
  File "component_binning.py", line 81, in gen_X
    compositMat = shuffled_compositMat[covIdxArr]
IndexError: index 94834869609936 is out of bounds for axis 0 with size 1509418

real	1m7.945s
user	0m38.402s
sys	0m4.808s

The coverage file was generated from converting the maxbin depth with the command from the readme file page.

Thanks in advance.

**Comment by ziyewang** [comment]
Hi,

It seems that the kmer_profile file contains contigs longer than 1000bp, but the coverage profile file contains all the contigs. Please remove the contigs no longer than 1000bp for the coverage profile file and the contig file as README, and give it another try.

"Remove the contigs no longer than 1000bp like this for the maxbin depth:

cat mb2_master_depth.txt | awk '{if ($2>1000) print $0 }' | cut -f -1,4- > coverage_profile_f1k.tsv

Remove the contigs no longer than 1000bp like this for contig file:
cd path_to_MetaBinner
cd scripts

python Filter_tooshort.py final.contigs.fa 1000
"

More details are given in README. Please feel free to let us know if you have any further questions.

Best,
Ziye

**Comment by EisenRa** [comment]
It seems that `gen_kmer.py` actually removes contigs including the value that the user specifies for the cutoff.

e.g. if the user selects 1000 as the threshold, contigs shorter than **AND including** 1000 will be removed.

I think this is due to the call in the python script on line 41:
```
        if seq_len <= length_threshold:
```

If it were **<** rather than **<=**, then contigs less than 1000 would be removed. To me this is a bit more intuitive, and it fits easier with other software. For example, with megahit you can specify a minimum contig length, meaning that you'd only have to run the `gen_kmer.py` script, and not bother filtering your contigs files/metabat coverage files.
